# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0028_auto_20171024_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peilbuis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'omschrijving')),
                ('rectangle_id', models.CharField(blank=True, help_text=b'ID van de bijbehorende SVG rectangle', max_length=50, null=True, verbose_name=b'rectangle ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Series', verbose_name=b'reeks')),
            ],
            options={
                'verbose_name_plural': 'peilbuizen',
            },
        ),
    ]
