# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flevoland', '0002_auto_20171115_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contents', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='piezometer',
            options={'verbose_name_plural': 'piezometers'},
        ),
    ]
