# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20171024_1521'),
        ('flevoland', '0003_auto_20171128_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_file_name', models.CharField(max_length=50)),
                ('rectangle1_id', models.CharField(max_length=50)),
                ('rectangle2_id', models.CharField(max_length=50)),
                ('meetlocatie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.MeetLocatie')),
                ('precipitation_per_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Series')),
                ('precipitation_per_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SVG_Metadata_set', to='data.Series')),
            ],
        ),
    ]
