# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20171024_1521'),
        ('flevoland', '0004_svgmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetext',
            name='meetlocatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.MeetLocatie'),
        ),
        migrations.AlterField(
            model_name='svgmetadata',
            name='meetlocatie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SVG_metadata', to='data.MeetLocatie'),
        ),
    ]
