# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20171024_1521'),
        ('flevoland', '0005_auto_20171129_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitetext',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='websitetext',
            unique_together=set([('meetlocatie', 'name')]),
        ),
    ]
